restore_registry: &RESTORE_REGISTRY
  restore_cache:
    key: registry
save_registry: &SAVE_REGISTRY
  save_cache:
    key: registry-{{ .BuildNum }}
    paths:
    - /usr/local/cargo/registry/index
deps_key: &DEPS_KEY
  key: deps-{{ checksum "~/rust-version" }}-{{ checksum "Cargo.lock" }}
restore_deps: &RESTORE_DEPS
  restore_cache:
    <<: *DEPS_KEY
save_deps: &SAVE_DEPS
  save_cache:
    <<: *DEPS_KEY
    paths:
    - target
    - /usr/local/cargo/registry/cache

version: 2
jobs:
  build:
    docker:
      - image: rust:1.63.0
        environment:
          RUSTFLAGS: -D warnings
    steps:
      - checkout
      - run: rustup component add rustfmt clippy
      - *RESTORE_REGISTRY
      - run: cargo generate-lockfile
      - *SAVE_REGISTRY
      - run: rustc --version > ~/rust-version
      - *RESTORE_DEPS
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all --all-targets
      - run: cargo test --all
      - run: cargo test --all --all-features
      - *SAVE_DEPS
  circle-all:
    docker:
    - image: busybox:1.34.1
    resource_class: small
    steps:
    - run:
        command: echo "All required jobs finished successfully"
workflows:
  version: 2
  build:
    jobs:
    - build:
        requires: []
        filters:
          tags:
            only: /.*/
    - circle-all:
        requires:
        - build
        filters:
          tags:
            only: /.*/
